"""DIMER inference package for the pinned ``microsoft/xclip-base-patch32`` checkpoint."""

from .pipeline import (
    DEFAULT_WEIGHTS_DIR,
    FRAME_SIZE,
    INPUT_SCHEMA,
    MAX_IMAGE_SIDE,
    MAX_LABEL_CHARS,
    MAX_LABELS,
    MAX_TEXT_TOKENS,
    MIN_IMAGE_SIDE,
    MIN_LABELS,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    NUM_FRAMES,
    XClipVideoClassificationPipeline,
    evaluation_report,
    format_labels,
    frames_from_animation,
    sample_frames,
    stage_missing_files,
    validate_clip,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "DEFAULT_WEIGHTS_DIR",
    "FRAME_SIZE",
    "INPUT_SCHEMA",
    "MAX_IMAGE_SIDE",
    "MAX_LABELS",
    "MAX_LABEL_CHARS",
    "MAX_TEXT_TOKENS",
    "MIN_IMAGE_SIDE",
    "MIN_LABELS",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "NUM_FRAMES",
    "XClipVideoClassificationPipeline",
    "evaluation_report",
    "format_labels",
    "frames_from_animation",
    "sample_frames",
    "stage_missing_files",
    "validate_clip",
    "validate_inputs",
    "verify_snapshot",
]
